WINDOW_WIDTH = 800
WINDOW_HEIGHT = 700

GAME_LEFT = -350
GAME_RIGHT = 350
GAME_BOTTOM = -260
GAME_TOP = 260
GRID_SIZE = 20
STARTING_LENGTH = 3
STARTING_SPEED = 150

BACKGROUND_COLOR = "#0B1021"
BORDER_COLOR = "#E6F1FF"
TEXT_COLOR = "#FFFFFF"
SNAKE_HEAD_COLOR = "#00FF99"
SNAKE_BODY_COLOR = "#73FBD3"
FOOD_COLOR = "#FF4D6D"
BONUS_FOOD_COLOR = "#FFD166"

NORMAL_FOOD_POINTS = 10
BONUS_FOOD_POINTS = 25
BONUS_FOOD_TIME = 6000

UP_KEYS = ("Up", "w", "W")
DOWN_KEYS = ("Down", "s", "S")
LEFT_KEYS = ("Left", "a", "A")
RIGHT_KEYS = ("Right", "d", "D")

ADMIN_MIN_POINTS = 1
ADMIN_MAX_POINTS = 1000
ADMIN_MIN_SPEED = 0.1
ADMIN_MAX_SPEED = 5.0
ADMIN_ANIMATION_MIN = 1
ADMIN_ANIMATION_MAX = 3

SNAKE_MESSAGE_COLOR = "#00FFFF"
ADMIN_MESSAGE_COLOR = "#FF00FF"
MENU_MESSAGE_COLOR = "#FFD700"
GAME_OVER_COLOR = "#FF3131"
PAUSED_COLOR = "#FFD700"
NAVIGATE_COLOR = "#B8C7CC"

ANIMATION_PICKUP_STEPS = 5
ANIMATION_GROW_STEPS = 5
ANIMATION_LEVEL_COLORS = ["#FFD700", "#FFA500", "#FF6347"]
ANIMATION_POPUP_STEPS = 10
ANIMATION_PICKUP_SCALE = 0.15
ANIMATION_GROW_SCALE = 0.14
ANIMATION_POPUP_OFFSET = 5
LEVEL_UP_MESSAGE_DURATION = 1000
BONUS_DROP_CHANCE = 0.25

ADMIN_MENU_OPTIONS = {
    "1": "ADJUST POINTS",
    "2": "ADJUST SPEED",
    "3": "ANIMATION LEVEL",
    "4": "BACK TO MENU",
}
